### ISSUE TITLE
你好，怎么才能在点击你的关于直销银行button的时候取消闪烁呢

### ISSUE THREAD

**Issue by DotaAntiMagic** [zhengwenming/ExpandTableView#2]
在点击关于直销银行按钮的时候，会有轻微的闪烁，是由于你的    [expandTable reloadSections:[NSIndexSet indexSetWithIndex:sender.tag-1] withRowAnimation:UITableViewRowAnimationAutomatic];造成的，但是我想取消掉点击直销银行按钮的轻微闪烁，又想保留扩展tableview的下拉动画，要怎么弄呢

**Comment by zhengwenming** [comment]
这个是系统自带的动画效果，UITableViewRowAnimationAutomatic这个是一个枚举，你都试试，看看有没有适合的，如果没有，那就没办法了。
